name: Test

on:
  pull_request: {}
  push:
    branches:
      - main

env:
  BUNDLE_WITHOUT: release

jobs:

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      #- name: Run tests
      #  run: bundle exec rake test
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
  foremanci:
    name: Foreman Plugin tests
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_hdm
  foremanci314:
    name: Foreman Plugin tests
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_hdm
      foreman_version: '3.14-stable'
  foremanci313:
    name: Foreman Plugin tests
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_hdm
      foreman_version: '3.13-stable'

  tests:
    needs:
      - rubocop
      - test
      - foremanci
      - foremanci314
      - foremanci313
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
